### ISSUE TITLE
A few problems with server code

### ISSUE THREAD

**Issue by neubig** [pcyin/tranX#17]
In trying to run the server code, I found a few problems:

1. First, parts of the command seem to assume you're in the `server` directory and parts assume that you're in the top directory. The following command worked for me from the top directory:

    `PYTHONPATH=. python server/app.py --config_file config/server/config_py3.json`

2. There are some package requirements that are not specified anywhere. I was able to fix them with the following command, but it'd probably be good to add them to the conda environment:

    `pip install flask python-rex`

3. I got stuck on this bug, which prevented it from working on atis: https://github.com/pcyin/tranX/issues/9

I can fix the first two and send a PR, but the second one I'm not sure where to get the requisite file. For the time being I'll try to work around this by disabling atis in the server.

**Comment by neubig** [comment]
One more problem:

4. While I was able to set up a server and get results by accessing http://server.name.cmu.edu:8081/ I'm not able to successfully access http://server.name.cmu.edu:8081/parser/conala/print%20hello . It gives me a 404...

**Comment by pcyin** [comment]
Thanks for reporting this! For 4., the correct URL it should be:

http://server.name.cmu.edu:8081/parse/conala/print%20hello

Try: http://moto.clab.cs.cmu.edu:8082/parse/conala/print%20hello
