### ISSUE TITLE
evaluation on a trained model

### ISSUE THREAD

**Issue by armheb** [pcyin/tranX#8]
Hi, how can we use the trained models and make predictions using them? for example, I want to input some text and generate the django code for it.
thanks.

**Comment by mellahysf** [comment]
Hi @armheb  
Did you found the solution ? can you tel me how ? 
Thank you.

**Comment by pcyin** [comment]
Hey! Sorry for the late reply! Have you checked our online demo? It uses [`StandalonePaser`](https://github.com/pcyin/tranX/blob/master/server/app.py#L91), which takes as input a raw utterance, preprocesses the utterance, parses it to a logical form, and then performs necessary post-processing steps.
